apiVersion: v1
kind: Service
metadata:
   name: companyms-svc
   labels:
     app: companyms
     

spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
     app: companyms
     
   